import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./theme-confing.css";
import "./globals.css";
import Navbar from "./components/Navbar";
import App from "./_app";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={poppins.variable}>
        <App>
          <Theme accentColor="cyan" radius="large">
          <Navbar></Navbar>
          <main>{children}</main>
          {/* <ThemePanel /> */}
          </Theme>
        </App>
      </body>
    </html>
  );
}
